// Original CTF text (without the duplication present in the previous version).
// The encrypted word is still hidden in the same passage of the report.
const transmission = [
  'Durante a era das Guerras Gálicas, a comunicação era vital para as operações militares. Para manter a segurança de suas mensagens, os generais precisavam de um método seguro e confiável. Foi nesse período que se desenvolveu um método de comunicação secreta, que permitia transmitir mensagens sem que fossem compreendidas pelos inimigos. A técnica envolvia a substituição de caracteres: cada letra da mensagem original era trocada por outra, seguindo uma regra pré-definida. Assim, apenas as pessoas autorizadas tinham acesso ao conteúdo.',
  'A técnica de substituição foi amplamente utilizada pelos militares romanos, que trocavam informações importantes sem o risco de serem descobertos. Os mensageiros, muitas vezes montados a cavalo, percorriam grandes distâncias carregando pergaminhos codificados. Caso fossem capturados, o conteúdo das mensagens permaneceria incompreensível para quem não conhecesse o código.',
  'Com o avanço das campanhas militares e a expansão do império, o sistema foi aprimorado. Alguns generais passaram a modificar a regra da substituição de tempos em tempos, tornando ainda mais difícil para os adversários decifrar os escritos interceptados. Apenas quem possuía a chave correta conseguia compreender as instruções enviadas pelo alto comando.',
  'O uso desse método tornou-se um segredo guardado entre os oficiais de maior confiança. Em tendas de campanha, à luz de tochas, escribas convertiam mensagens comuns em códigos enigmáticos antes de enviá-las aos campos de batalha. Muitas decisões cruciais, de ataques-surpresa a movimentações estratégicas, dependeram dessa forma de comunicação protegida.',
  'Além do uso em tempos de guerra, esse método de cifragem também protegia documentos administrativos e tratados secretos. Durante as negociações com povos aliados ou a espionagem xowlpdwr contra inimigos, os romanos utilizavam mensagens codificadas para garantir que informações sigilosas não caíssem em mãos erradas. A confiabilidade desse sistema ajudou a consolidar a superioridade estratégica de Roma por décadas.',
  'Com a queda do Império Romano e o surgimento de novas civilizações, o método não foi esquecido. Reis e comandantes medievais redescobriram a técnica, adaptando-a às suas necessidades. Na Idade Média, mensageiros transportavam correspondências sigilosas entre monarcas usando sistemas de substituição semelhantes — e o mesmo ocorreu nas grandes navegações, quando exércitos e navegadores protegiam suas comunicações com códigos.',
  'Ao longo da história, essa técnica inspirou formas mais sofisticadas de criptografia. A ideia de transformar mensagens comuns em algo indecifrável para quem não possui a chave tornou-se a base da segurança da informação. Ainda hoje, o princípio por trás dela é aplicado em meios digitais para proteger dados pessoais, transações financeiras e comunicações sigilosas.',
];

export default transmission;
